# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'STFollowLayout' do

pod 'STFollowLayout', '~> 1.0.0'
pod 'SDWebImage'
pod 'MJExtension'
pod 'MJRefresh'
end
